export enum PREFIX {
  GET = "GET",
  POST = "POST",
  PUT = "PUT",
  DELETE = "DELETE",
  // ---COMMON
  MULTIPLE = "MULTIPLE",
  // ---PRODUCTS
  DEFAULT_CATEGORIES = "DEFAULT_CATEGORIES",
  CATEGORIES = "CATEGORIES",
  DEFAULT_EXPENSE_TEMPLATES = "DEFAULT_EXPENSE_TEMPLATES",
  EXPENSE_TEMPLATES = "EXPENSE_TEMPLATES",
  ACTIVE_BUDGET_PLAN = "ACTIVE_BUDGET_PLAN",
  EXPENSES = "EXPENSES",
  // ---DASHBOARD
  DASHBOARD_OVERVIEW = "DASHBOARD_OVERVIEW",
}
