export enum PREFIX {
  GET = "GET",
  POST = "POST",
  PUT = "PUT",
  DELETE = "DELETE",
  // ---COMMON
  MULTIPLE = "MULTIPLE",
  // ---PRODUCTS
  DEFAULT_CATEGORIES = "DEFAULT_CATEGORIES",
  CATEGORIES = "CATEGORIES",
  DEFAULT_EXPENSE_TEMPLATES = "DEFAULT_EXPENSE_TEMPLATES",
  EXPENSE_TEMPLATES = "EXPENSE_TEMPLATES",
}
