export default {
  BASE_URL_API: process.env.NEXT_PUBLIC_BASE_URL_API,
  EXPIRE_DAYS: process.env.NEXT_PUBLIC_EXPIRE_DAYS,
  TOKEN_KEYNAME: process.env.NEXT_PUBLIC_TOKEN_KEYNAME,
  REFRESH_TOKEN_KEYNAME: process.env.NEXT_PUBLIC_REFRESH_TOKEN_KEYNAME,
};
